import type {Professional} from './types';
export const professionals:Professional[] = [
{id:'raj',name:'Sagar Rana',trade:'Plumber',city:'Bengaluru',area:'Indiranagar',experience:8,rating:4.9,reviews:48,rate:5000,available:true,skills:['Bathroom fittings','Leak repairs','Pipe installation'],tools:['Pipe wrench','Power drill','Pipe cutter','Pressure tester'],bio:'From a small leak to a complete bathroom renovation, I take pride in neat, lasting work. Serving homes across East Bengaluru for 8 years.',work:[{id:'r1',title:'A fresh start for this bathroom',description:'Complete concealed plumbing and fixture installation for a 2BHK renovation in Indiranagar.',kind:'image',src:'/images/plumbing.jpg',tools:['Pipe wrench','Pipe cutter']}]},
{id:'amit',name:'Amit Sharma',trade:'Electrician',city:'Bengaluru',area:'Whitefield',experience:6,rating:4.8,reviews:36,rate:450,available:true,skills:['Home wiring','Lighting','MCB installation'],tools:['Digital multimeter','Wire stripper','Insulated screwdriver','Voltage tester'],bio:'Residential wiring, lighting upgrades and electrical troubleshooting. Clean finishes and careful work, every time.',work:[{id:'a1',title:'Wiring, done right.',description:'Organised the electrical distribution board and labelled circuits for a residential project.',kind:'image',src:'/images/electrical.jpg',tools:['Digital multimeter','Wire stripper']}]},
{id:'suresh',name:'Suresh Patel',trade:'Carpenter',city:'Bengaluru',area:'HSR Layout',experience:12,rating:4.9,reviews:72,rate:800,available:false,skills:['Modular kitchens','Custom furniture','Woodwork'],tools:['Circular saw','Cordless drill','Wood router','Orbital sander'],bio:'Custom woodwork that makes your space feel like home. Specialising in fitted storage and modular kitchens.',work:[{id:'s1',title:'Built to fit. Made to last.',description:'A custom modular kitchen with soft-close cabinets and a natural wood finish.',kind:'image',src:'/images/carpentry.jpg',tools:['Circular saw','Wood router']}]},
{id:'imran',name:'Imran Khan',trade:'Painter',city:'Bengaluru',area:'Koramangala',experience:7,rating:4.7,reviews:29,rate:600,available:true,skills:['Interior painting','Wall textures','Waterproofing'],tools:['Paint roller','Airless sprayer','Sanding machine','Extension ladder'],bio:'Thoughtful preparation, smooth walls and a clean handover. Interior painting and textured finishes for homes.',work:[{id:'i1',title:'A little colour, a big difference',description:'Interior wall preparation and two-coat painting for a living room refresh.',kind:'image',src:'/images/painting.jpg',tools:['Paint roller','Sanding machine']}]},
{id:'deepak',name:'Deepak Yadav',trade:'AC technician',city:'Bengaluru',area:'Marathahalli',experience:5,rating:4.8,reviews:41,rate:550,available:true,skills:['AC installation','Deep cleaning','Cooling repairs'],tools:['Manifold gauge','Vacuum pump','Clamp meter','Service jet'],bio:'Installation, preventive maintenance and cooling diagnosis for split and window air conditioners.',work:[{id:'d1',title:'Ready for the summer',description:'Indoor unit deep cleaning and cooling performance inspection.',kind:'image',src:'/images/ac.jpg',tools:['Service jet','Clamp meter']}]},
{id:'vikram',name:'Vikram Singh',trade:'Electrician',city:'Delhi',area:'Rohini',experience:9,rating:4.9,reviews:56,rate:5000,available:true,skills:['Lighting','Home wiring','Fan installation'],tools:['Voltage tester','Power drill','Wire stripper'],bio:'Dependable electrical installation and repairs across North Delhi.',work:[{id:'v1',title:'Every connection matters',description:'Electrical panel inspection and residential circuit maintenance.',kind:'image',src:'/images/electrical.jpg',tools:['Voltage tester']}]},
];
export const initialProfile:Professional={id:'me',name:'Arjun Verma',trade:'Electrician',city:'Bengaluru',area:'Indiranagar',experience:4,rating:0,reviews:0,rate:450,available:true,skills:['Home wiring','Lighting'],tools:['Digital multimeter','Cordless drill'],bio:'I help homeowners with electrical repairs, new fittings and lighting installations.',work:[]};
